global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: storage-server
    static_configs:
      - targets: ["storage-server:9012"]

  - job_name: embedder-worker-metrics
    static_configs:
      - targets: ["embedder-worker:9108"]

  - job_name: vlm-worker-metrics
    static_configs:
      - targets: ["vlm-worker:9109"]
