apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avsp.fullname" . }}-secrets
  namespace: {{ include "avsp.namespace" . }}
  labels:
    {{- include "avsp.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.db | quote }}
  MINIO_ROOT_USER: {{ .Values.secrets.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.secrets.minio.rootPassword | quote }}
  CLICKHOUSE_USER: {{ .Values.secrets.clickhouse.user | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhouse.password | quote }}
  CLICKHOUSE_DB: {{ .Values.secrets.clickhouse.db | quote }}
  STORAGE_WRITE_TOKEN: {{ .Values.secrets.storage.writeToken | quote }}
